### ISSUE TITLE
Could not open library 'libsecp256k1'

### ISSUE THREAD

**Issue by icattlecoder** [nervosnetwork/ckb-demo-ruby-sdk#13]
Followed the README docs,  after run `bundle exec pry -r ./lib/ckb/wallet.rb`, I got an error on MacOS with ruby 2.3.7p456:
```
bundler: failed to load command: pry (/usr/local/bin/pry)
LoadError: Could not open library 'libsecp256k1': dlopen(libsecp256k1, 0x0005): dlopen(): file not found: libsecp256k1.
Could not open library 'libsecp256k1.dylib': dlopen(libsecp256k1.dylib, 0x0005): dlopen(): file not found: libsecp256k1.dylib
  /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.25/lib/ffi/library.rb:145:in `block in ffi_lib'
  /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `map'
  /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.25/lib/ffi/library.rb:99:in `ffi_lib'
  /Library/Ruby/Gems/2.3.0/gems/bitcoin-secp256k1-0.4.0/lib/secp256k1/c.rb:9:in `<module:C>'
  /Library/Ruby/Gems/2.3.0/gems/bitcoin-secp256k1-0.4.0/lib/secp256k1/c.rb:6:in `<module:Secp256k1>'
  /Library/Ruby/Gems/2.3.0/gems/bitcoin-secp256k1-0.4.0/lib/secp256k1/c.rb:5:in `<top (required)>'
  /Library/Ruby/Gems/2.3.0/gems/bitcoin-secp256k1-0.4.0/lib/secp256k1.rb:3:in `require'
  /Library/Ruby/Gems/2.3.0/gems/bitcoin-secp256k1-0.4.0/lib/secp256k1.rb:3:in `<top (required)>'
  /Users/xxx/projects/ckb-demo-ruby-sdk/lib/ckb/utils.rb:1:in `require'
  /Users/xxx/projects/ckb-demo-ruby-sdk/lib/ckb/utils.rb:1:in `<top (required)>'
  /Users/xxx/projects/ckb-demo-ruby-sdk/lib/ckb/api.rb:1:in `require_relative'
  /Users/xxx/projects/ckb-demo-ruby-sdk/lib/ckb/api.rb:1:in `<top (required)>'
  /Users/xxx/projects/ckb-demo-ruby-sdk/lib/ckb/wallet.rb:1:in `require_relative'
  /Users/xxx/projects/ckb-demo-ruby-sdk/lib/ckb/wallet.rb:1:in `<top (required)>'
  /Library/Ruby/Gems/2.3.0/gems/pry-0.12.2/lib/pry/pry_class.rb:113:in `require'
  /Library/Ruby/Gems/2.3.0/gems/pry-0.12.2/lib/pry/pry_class.rb:113:in `block in load_requires'
  /Library/Ruby/Gems/2.3.0/gems/pry-0.12.2/lib/pry/pry_class.rb:112:in `each'
  /Library/Ruby/Gems/2.3.0/gems/pry-0.12.2/lib/pry/pry_class.rb:112:in `load_requires'
  /Library/Ruby/Gems/2.3.0/gems/pry-0.12.2/lib/pry/pry_class.rb:156:in `final_session_setup'
  /Library/Ruby/Gems/2.3.0/gems/pry-0.12.2/lib/pry/cli.rb:79:in `parse_options'
  /Library/Ruby/Gems/2.3.0/gems/pry-0.12.2/bin/pry:7:in `<top (required)>'
  /usr/local/bin/pry:22:in `load'
  /usr/local/bin/pry:22:in `<top (required)>'
```

No experience in ruby, how should I do?

---
### Solution
https://github.com/nervosnetwork/ckb-demo-ruby-sdk/issues/13#issuecomment-447706499

- [ ] Mention that secp256k1 should be installed manually in README

**Comment by xxuejie** [comment]
This is actually a dependency in the gem [bitcoin-secp256k1](https://github.com/cryptape/ruby-bitcoin-secp256k1), you can follow the [prerequiste](https://github.com/cryptape/ruby-bitcoin-secp256k1#prerequiste) part in the gem to install secp256k1 library locally.

**Comment by xxuejie** [comment]
@ashchan I'm also thinking maybe just switching a different gem which doesn't require dynamic linking, it might ease the installation step a bit, thoughts?

**Comment by icattlecoder** [comment]
> This is actually a dependency in the gem bitcoin-secp256k1, you can follow the prerequiste part in the gem to install secp256k1 library locally.
------------
It works, thanks! But i got another problem, see #14

**Comment by ashchan** [comment]
@xxuejie Will add note to the README.

**Comment by doitian** [comment]
> @xxuejie Will add note to the README.

@ashchan will or @xxuejie will?

**Comment by ashchan** [comment]
@doitian I'll do that.
